### ISSUE TITLE
What are the official dependency coordinates for XOM?

### ISSUE THREAD

**Issue by lukewpatterson** [elharo/xom#101]
Let's say I'm writing a non-toy project, and want to consume XOM.  I'm using Ant+Ivy, Maven, Gradle, SBT,  etc. ...  What coordinates do I use to import XOM?

Those build tools declare external dependencies using coordinates.  Manually dropping an external JAR into source control is not easily supported by most build tools and would be frowned upon by most consuming projects.

**If** a goal is to make the project consumable, it needs to be in a Maven repo.  I want to stress that this doesn't mean consumers must use "Maven the build tool" when consuming the JAR from a "Maven-layout repository".

Maven Central and Bintray JCenter are the 2 most popular repositories.

XOM is great and I'd like to use it but I can't because of the current lack of standard publishing practices.

**Comment by elharo** [comment]
1.2.10 is in Maven central somewhere. com.io7:xom or some such. 

1.3.0 will be there eventually if Sonatype allows.

**Comment by elharo** [comment]
There are no "official" dependency coordinates for XOM.

**Comment by lukewpatterson** [comment]
It's your project and you can set the goals, of course.  I just wanted to make sure you realized that **if** easy/standard-path consumption is a goal, then the project needs official coordinates so people can know you built it and they can trust the executable code they are downloading.

Some people give up on using XOM when they realize it isn't easy to use in a non-toy project.  But like I said, it's your project and you set the goals.
