### ISSUE TITLE
Prolog control

### ISSUE THREAD

**Issue by cbondeson** [elharo/xom#106]
Consider adding the ability to control whether a prolog is added and what that prolog contains. I process XML using Xalan callouts from XSLT into the Java tier. I have functions which iterate and generate XML using BaseX. Each loop would generate an XML which is concatenated into a output string. I only need the prolog on the first and not each iteration. I created an overload to handle this. This product was great to get away from the extremely slow Java built into DOM processing. Excellent workl

**Comment by elharo** [comment]
There's not enough detail here to understand the request, but it's very unlikely that anything like this will be considered since there's probably a way to do what you're trying to do already
