### ISSUE TITLE
Everytime a document is built, freememory calls System.gc()

### ISSUE THREAD

**Issue by freddy-rabiller** [elharo/xom#113]
Since commit [encoding test needs more memory](https://github.com/elharo/xom/commit/ad5cb71a0bd72ecc40a01c156c80ebea7313c647), _nu.xom.XOMHandler#freeMemory_ performs an explicit _System.gc()_ calls.

It can lead to a very huge performance penalty. I don't understand the need here. It seems to be a mistake left there after leading some tests. Could you confirm ?

**Comment by vlastimil-dolejs** [comment]
I can confirm the performance issues caused by this. I build a lot of small documents and it completely destroys the performance of the application.

**Comment by elharo** [comment]
Do you have some measurements or a test case?

**Comment by vlastimil-dolejs** [comment]
I have analyzed it in VisualVM and don't have benchmark.
You can simulate the problem by running this in loop:
```
document = new Builder().build(xmlAsString, "");
```
Ty it with 1.2.5 vs 1.3.2

**Comment by elharo** [comment]
Which garbage collector algorithms are you using or have you tried?

**Comment by vlastimil-dolejs** [comment]
Tested on OpenJDK 11 and 13. Both with default G1 garbage collector.

**Comment by elharo** [comment]
This went in here: https://github.com/elharo/xom/pull/23/files

Versions between that and 1.3.2 probably weren't widely used.

**Comment by elharo** [comment]
xom:xom:1.3.3 is in the repos now with this fix. Please give it a try and let me know if it works.
