### ISSUE TITLE
Test failure: testIllegalIP6Addresses

### ISSUE THREAD

**Issue by io7m** [elharo/xom#12]
In `nu.xom.tests.VerifierTest`:

```
Allowed illegal IPv6 address: ::FFFF:129.144.52.+22

junit.framework.AssertionFailedError: Allowed illegal IPv6 address: ::FFFF:129.1144.52.+22
at nu.xom.tests.VerifierTest.testIIllegalIP6Addresses(Unknown Source)
```

**Comment by elharo** [comment]
That's strange. Might be an actual bug. I'll have to look at it, and remind myself why this test is there and how the code works. Probably something about namespace URIs or system IDs.

**Comment by elharo** [comment]
see http://www.faqs.org/rfcs/rfc2732.html
