### ISSUE TITLE
XOM 1.3.4 jar in Maven Central doesn't contain Automatic-Module-Name

### ISSUE THREAD

**Issue by anthonyvdotbe** [elharo/xom#142]
From the [release notes](http://xom.nu/history.html), and from #127, I'd assume that the [jar in Maven Central](https://repo1.maven.org/maven2/xom/xom/1.3.4/xom-1.3.4.jar) would include the Automatic-Module-Name manifest entry, but it doesn't.
Since htmlparser is planning to modularize itself (see https://github.com/validator/htmlparser/issues/14), but depends on XOM, it would be very helpful if a XOM release with Automatic-Module-Name would be available in Maven Central.

**Comment by elharo** [comment]
You're right. It's a bug. Took me a while to find my mistake, but I see it now. I'll push a fix soon. Thanks.
