### ISSUE TITLE
Compatibility with standard XML Apis

### ISSUE THREAD

**Issue by buko** [elharo/xom#145]
Just discovered xom and like what what we see. The support for xml:id is particularly nice; Xerces doesn't support xml:id and this is a constant source of pain. One question that comes up is how compatible Xom is with standard APIs like SAX, StAX, JAXB, and w3c.dom. The Xom documentation doesn't speak to this...

In our system there are several cases where w3c.dom and JAXB objects are written to and read from XMLStreamWriters and XMLStreamReaders. Does XOM support this?

What about existing systems that work with w3c.dom? Is there an efficient way to convert xom to w3c.dom?  Or must the xml be serialized and deserialized?

BTW: xom has its own xinclude support but we use and are fine with [Xerces' built in support for XInclude](https://xerces.apache.org/xerces2-j/faq-xinclude.html). I assume it's okay to continue to use this as long as we continue to set the XInclude feature.

**Comment by elharo** [comment]
You can ask these sorts of questions on the xom-interest mailing list.
