### ISSUE TITLE
Dependency on JDK internal classes

### ISSUE THREAD

**Issue by jfdenise** [elharo/xom#155]
Using JDK16, our project [WildFly Bootable JAR ](https://github.com/wildfly-extras/wildfly-jar-maven-plugin) fails due to nu.xom.JDK15XML1_0Parser accessing internal classes.
It seems a workaround for some old JDK 5 beta versions. Could we have a xom version without this internal access?
Thank-you.
PS: The original bug report: https://github.com/wildfly-extras/wildfly-jar-maven-plugin/issues/206
NB: We are in a context were we are excluding xerces:xercesImpl classes from xom, and fallback to the JDK15XML1_0Parser

**Comment by elharo** [comment]
Thanks for the report. I'll look into that when I get some free time.

**Comment by elharo** [comment]
Despite the comment, I don't think this class is just about the betas of JDK 1.5. Likely that was the first version where this became a problem. (XOM dates back to Java 1.4 days.)

**Comment by elharo** [comment]
This is JEP 396. As a workaround, you can use `--illegal-access=permit`. I'll have to think about how best to adjust the code to avoid this.

**Comment by elharo** [comment]
Good news. On further investigation it seems that class is not actually used anymore, so I can simply remove it.

**Comment by jfdenise** [comment]
@elharo , are you deploying latest releases in Maven central? I can only see 1.2.10. Thank-you.

**Comment by elharo** [comment]
you likely aren't using the correct group ID

**Comment by jfdenise** [comment]
@elharo , you are right our project depended on com.io7m.xom:xom, I found the latest release in xom:xom
