### ISSUE TITLE
Duplicate dependences import

### ISSUE THREAD

**Issue by huangshijie** [elharo/xom#158]
Hi,

I found project import different version of xml-apis.

Maybe need to exclude xml-apis in xalan and xerces.

![image](https://user-images.githubusercontent.com/10737804/111751913-0138b200-88d0-11eb-86c4-ea35a7917a59.png)

Thanks,
Alex

**Comment by elharo** [comment]
more likely, update xml-apis, I'll have to check

**Comment by huangshijie** [comment]
Sure, and thanks for your quick reply.

**Comment by elharo** [comment]
Hmm, now that we require Java 5 or later I think I can simply remove this dependency. It should always be in the JDK.
