### ISSUE TITLE
Add location information to Node class

### ISSUE THREAD

**Issue by dmlloyd** [elharo/xom#18]
It would be useful to have optional location information (line, column, character offset int fields, and ideally base URI or some way to acquire it) on the Node class which would allow better diagnostics to be presented to users in the event of an application error.

Such a solution should be resilient with respect to XInclude, so that a node which is examined would have the location information of the physical document that the Node in question originated from.  Also it would be useful to be able to recursively list the include points in this case so the user can understand exactly how the document was included.  Making the location information mutable might also be handy in cases where a XOM tree is built up programmatically.

This would also be useful in creating adapters between StAX and XOM, which is an idea I'm tinkering with at the moment.

The memory overhead should be very minimal (four fields totalling around 16-20 bytes per Node typically).

WDYT?

**Comment by dmlloyd** [comment]
I would also note that it *is* possible to do this via custom subclasses, but it is difficult to integrate and also would seem to require a separate ```nu.xom.Builder``` implementation/subclass or equivalent.

**Comment by dmlloyd** [comment]
Here's something else to note: frameworks like SAX and StAX normally include public ID/system ID in the location information.  I'm not certain this is strictly useful though, especially in the XOM case, as the DocType would also contain this information.

**Comment by elharo** [comment]
I was thinking about this a few months ago, bu8t at the end of the day the answer is still the same as it was 10 years ago. The use case is text-focused editors, and that's not something this API, or any of the underlying APIs we depend on, address. To solve this problem you really need to start from scratch with a different parser not based on SAX. 

Also, if we accept that 16-20 bytes per node overhead, that's still way more than I want to pay.

**Comment by dmlloyd** [comment]
SAX does provide location information though, if that's what you mean.

**Comment by elharo** [comment]
It's not guaranteed, reliable, complete, or accurate.

**Comment by dmlloyd** [comment]
It doesn't have to be, it only has to be best-effort, to give the user a starting point in diagnostics.  This is no different from any other location-aware JAXP framework.

For example it's OK to only have a line number, or for the line number to point at a start element when reporting on missing content.

**Comment by dmlloyd** [comment]
The JAXP convention is to report -1 for unknown location element (line, column, character position).

**Comment by dmlloyd** [comment]
In case you change your mind... it seems like all that is needed is something like this: https://gist.github.com/dmlloyd/d07b81eef6fc6559fbcb3b9ea6464e12

**Comment by dmlloyd** [comment]
Well it's been a year.  Have you changed your mind yet? ;)

**Comment by elharo** [comment]
I thought about this but first, it adds extra memory to each node object and XOM tries really hard to minimize memory footprint.

More significantly, XOM takes a hard line on not representing lexical information such as CDATA sections, whitespace inside tags, and entity references, all of which get involved in line numbers.

I've thought about ways one might glue lexical information onto a XOM tree in such a way it doesn't interfere with the main API, but so far I don't have anything I like.
