### ISSUE TITLE
tag for 1.2.10

### ISSUE THREAD

**Issue by wltjr** [elharo/xom#19]
Seem to be missing a tag for 1.2.10/XOM_1210 maybe 1f1d628, ```git tag XOM_1210 1f1d628``` thank  you! :)

**Comment by elharo** [comment]
There's no guarantee or promise that there will be tags for releases, especially ones created before the project moved to Github.

**Comment by wltjr** [comment]
Tags are quick and easy. There is no reason not to other than to be difficult. I have already forked and tagged for my needs. Thanks once again for the lack of cooperation!
