### ISSUE TITLE
Add Maven documentation

### ISSUE THREAD

**Issue by Forage** [elharo/xom#2]
It would be good to add some additional Maven documentation to the project files to tell which version should be gotten from where.

Currently you have xom : xom containing up to 1.2.5 and com.io7m.xom : xom containing just 1.2.10 in the central Maven repository. Combined with 1.2.10 missing here on GitHub (issue #1) it's doesn't give developers the assurance which version they should get from where. For me it feels like 1.2.10 has now been added by a 3rd party, which makes it less trustworthy.

**Comment by elharo** [comment]
I do not support Maven. Everything on Maven central is the work of third parties. You'd have to talk to them.

**Comment by stokito** [comment]
ok, but who will upload an artifact to Maven Central? Can I ping someone?
