### ISSUE TITLE
Clarify minimum Java version

### ISSUE THREAD

**Issue by jelovirt** [elharo/xom#42]
README says

> It requires Java 1.2 or later. 

But the Ant file uses Java 1.6 for compiling. Documentation should be updated to correctly define the minumum Java version.

**Comment by elharo** [comment]
The current version requires 1.2. The next version, 1.2.11 will likely require 1.6 mostly because these days it's hard to find a compiler that supports 1.2.

**Comment by elharo** [comment]
updated the docs
