### ISSUE TITLE
Update the xom entry in Maven Central

### ISSUE THREAD

**Issue by OtakuSenpai** [elharo/xom#90]
The Xom artifact in maven central is from [2010(1.2.5)](https://search.maven.org/artifact/xom/xom/1.2.5/jar) while the current version is 1.2.11.
Please update the version in the maven central.

**Comment by subwiz** [comment]
I tried jitpack, and that doesn't seem to be building.

https://jitpack.io/#elharo/xom/

**Comment by elharo** [comment]
I tried to upload 1.3.0 and got

Artifact upload failed.
Invalid maven artifacts: [xom-maven-1.3.0.jar, xom-maven-1.3.0.jar.asc, xom-maven-1.3.0.pom, xom-maven-1.3.0.pom.asc]

It's not immediately clear why it failed. I don't know how much time I have to debug this.

**Comment by elharo** [comment]
I suspect jitpack is assuming things about the build system that aren't true. It may not work with non-Maven projects.

**Comment by elharo** [comment]
I was able to upload the individual artifacts rather than bundle.jar, all checks passed, and the repository was closed.

 
https://oss.sonatype.org/content/repositories/xom-1000/

However I do not see a "Release" button anywhere

**Comment by elharo** [comment]
Released and discovered the artifact is off. Bleah.

**Comment by elharo** [comment]
1.3.2 is released.
